export { userLoggedIn } from './userLoggedIn'
export { renderComponent } from '../tools/renderComponent.js'
export { renderBasicLayout } from './renderBasicLayout'
export { changeCovidInfo } from '../layouts/Sidebar/changeCovidInfo.js'
export { renderVisitModal } from './renderVisitModal'
export { fillTableList } from './localData'
