image: node:latest

stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  cache:
    paths:
      - node_modules/
  script:
    - npm ci

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - VITE_OPENAI_KEY=$VITE_OPENAI_KEY npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - dev
