export { registrationImg } from './registrationImg.js'
export { LoginForm } from './loginForm'
export { validateUser } from './validateUser'
export { Registration } from './Registration'
export { covidData } from './fetchCovid'
// export { test } from './test'
