export { registrationImg } from './registrationImg.js'
export { loginForm } from './loginForm'
export { validateUser } from '../../modules/validateUser.js'
export { Registration } from './Registration'
export { covidData } from './fetchCovid'
export { loginFormHandler } from './loginFormHandler'
