export { drawDoctorsNames } from './docotrName'
export { drawDepartment } from './department'
export { showElements } from './showElement'
export { closeModalVisit } from './visitClosed'
export { request } from './fetch'
export { find, findAll } from './find'
export { create } from './create.js'
export { random } from './random.js'
