export { Registration, loginForm } from './Registration'
export { Dashboard, initCharts, initFilters } from './Dashboard'
export { Dropdown, createDropdown } from './Dropdown'
export { createInput } from './Input/createInput'
export { loginFormHandler } from './Registration'
export { initBot } from './Support/initBot'
